version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./react-front:/app
    #depends_on:
     # - backend

  #backend:
   # image: backend-image
    # Add any additional configuration for your backend container here for new features
